-- Active: 1734387683822@@127.0.0.1@5432@gestion_clientes

CREATE TABLE clientes (
    id SERIAL,
    nombre VARCHAR(50) NOT NULL,
    email VARCHAR(50)
);

DROP TABLE todos;

CREATE TABLE todos (
    id UUID,
    title VARCHAR(50) NOT NULL,
    done BOOLEAN DEFAULT FALSE
);

INSERT INTO
    clientes (nombre, email)
VALUES (
        'Juan Pérez',
        'juan.perez@example.com'
    ),
    (
        'María Gómez',
        'maria.gomez@example.com'
    ),
    (
        'Carlos Rodríguez',
        'carlos.rodriguez@example.com'
    ),
    (
        'Ana Fernández',
        'ana.fernandez@example.com'
    ),
    (
        'Luis Martínez',
        'luis.martinez@example.com'
    ),
    (
        'Laura García',
        'laura.garcia@example.com'
    ),
    (
        'Pedro Sánchez',
        'pedro.sanchez@example.com'
    ),
    (
        'Marta López',
        'marta.lopez@example.com'
    ),
    (
        'Jorge Díaz',
        'jorge.diaz@example.com'
    ),
    (
        'Lucía Ramírez',
        'lucia.ramirez@example.com'
    ),
    (
        'Ricardo Torres',
        'ricardo.torres@example.com'
    ),
    (
        'Sofía Vargas',
        'sofia.vargas@example.com'
    ),
    (
        'Andrés Castillo',
        'andres.castillo@example.com'
    ),
    (
        'Elena Morales',
        'elena.morales@example.com'
    ),
    (
        'Miguel Reyes',
        'miguel.reyes@example.com'
    ),
    (
        'Gabriela Cruz',
        'gabriela.cruz@example.com'
    ),
    (
        'Fernando Herrera',
        'fernando.herrera@example.com'
    ),
    (
        'Patricia Ruiz',
        'patricia.ruiz@example.com'
    ),
    (
        'Diego Mendoza',
        'diego.mendoza@example.com'
    ),
    (
        'Rosa Jiménez',
        'rosa.jimenez@example.com'
    );

SELECT * FROM clientes;

INSERT INTO
    todos
VALUES (
        DEFAULT,
        'Crear Base de datos',
        DEFAULT
    ),
    (
        DEFAULT,
        'Crear controlladores',
        DEFAULT
    ),
    (
        DEFAULT,
        'Crear Modelos',
        DEFAULT
    );

SELECT * FROM todos;

SELECT * FROM inmuebles;
-- Inmuebles
CREATE TABLE inmuebles (
    id SERIAL PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    descripcion TEXT,
    tipo VARCHAR(50) NOT NULL,
    ubicacion VARCHAR(255) NOT NULL,
    precio NUMERIC(15, 2) NOT NULL,
    habitaciones INTEGER NOT NULL,
    banos INTEGER NOT NULL,
    metros_cuadrados INTEGER NOT NULL,
    fecha_publicacion DATE NOT NULL DEFAULT CURRENT_DATE,
    disponible BOOLEAN NOT NULL DEFAULT TRUE,
    antiguedad INTEGER,
    pisos INTEGER,
    garage BOOLEAN DEFAULT FALSE,
    amueblado BOOLEAN DEFAULT FALSE,
    mascotas_permitidas BOOLEAN DEFAULT FALSE,
    area_exterior NUMERIC(15, 2),
    servicios_adicionales TEXT,
    propietario_contacto VARCHAR(255),
    tipo_energia VARCHAR(50) DEFAULT 'Convencional',
    estado VARCHAR(50) DEFAULT 'Nuevo',
    latitud NUMERIC(10, 6),
    longitud NUMERIC(10, 6)
);

INSERT INTO
    inmuebles (
        titulo,
        descripcion,
        tipo,
        ubicacion,
        precio,
        habitaciones,
        banos,
        metros_cuadrados,
        fecha_publicacion,
        disponible,
        antiguedad,
        pisos,
        garage,
        amueblado,
        mascotas_permitidas,
        area_exterior,
        servicios_adicionales,
        propietario_contacto,
        tipo_energia,
        estado,
        latitud,
        longitud
    )
VALUES (
        'Casa en Las Condes',
        'Casa moderna en sector exclusivo con jardín amplio.',
        'Casa',
        'Las Condes, Santiago',
        250000000,
        4,
        3,
        250,
        '2024-01-15',
        TRUE,
        10,
        2,
        TRUE,
        TRUE,
        TRUE,
        50,
        'Piscina y quincho',
        'catalina.valdes@gmail.com',
        'Eléctrica',
        'Usado',
        -33.408586,
        -70.567725
    ),
    (
        'Departamento en Providencia',
        'Departamento con vista al cerro San Cristóbal.',
        'Apartamento',
        'Providencia, Santiago',
        120000000,
        2,
        2,
        90,
        '2024-02-10',
        TRUE,
        5,
        1,
        TRUE,
        FALSE,
        TRUE,
        NULL,
        'Gimnasio y piscina',
        'rodrigo.perez@hotmail.com',
        'Solar',
        'Nuevo',
        -33.426319,
        -70.615287
    ),
    (
        'Terreno en Chicureo',
        'Terreno ideal para construir casa de lujo.',
        'Terreno',
        'Chicureo, Colina',
        180000000,
        0,
        0,
        1200,
        '2024-01-20',
        TRUE,
        NULL,
        NULL,
        FALSE,
        FALSE,
        FALSE,
        NULL,
        'Cercano a colegios y supermercados',
        'maria.lopez@terrenos.cl',
        'N/A',
        'Nuevo',
        -33.294259,
        -70.666667
    ),
    (
        'Casa en Viña del Mar',
        'Casa con vista al mar, cercana a Reñaca.',
        'Casa',
        'Reñaca, Viña del Mar',
        350000000,
        5,
        4,
        300,
        '2024-03-05',
        TRUE,
        8,
        2,
        TRUE,
        TRUE,
        TRUE,
        70,
        'Terraza con jacuzzi',
        'ignacio.diaz@gmail.com',
        'Eléctrica',
        'Usado',
        -32.970684,
        -71.551818
    ),
    (
        'Departamento en Valparaíso',
        'Departamento en cerro Alegre con terraza.',
        'Apartamento',
        'Cerro Alegre, Valparaíso',
        95000000,
        3,
        2,
        100,
        '2024-02-22',
        TRUE,
        12,
        1,
        TRUE,
        FALSE,
        TRUE,
        15,
        'Vista panorámica al puerto',
        'camila.sanchez@valpo.cl',
        'Convencional',
        'Usado',
        -33.045856,
        -71.619803
    ),
    (
        'Terreno en Puerto Varas',
        'Terreno amplio con vista al lago Llanquihue.',
        'Terreno',
        'Puerto Varas, Los Lagos',
        250000000,
        0,
        0,
        2000,
        '2024-04-01',
        TRUE,
        NULL,
        NULL,
        FALSE,
        FALSE,
        FALSE,
        NULL,
        'Acceso cercano a la playa del lago',
        'daniel.gutierrez@terrenos.com',
        'N/A',
        'Nuevo',
        -41.319987,
        -72.986672
    ),
    (
        'Casa en La Serena',
        'Casa familiar con excelente ubicación.',
        'Casa',
        'La Serena, Coquimbo',
        125000000,
        3,
        2,
        140,
        '2024-02-18',
        TRUE,
        15,
        1,
        TRUE,
        TRUE,
        TRUE,
        30,
        'Patio y quincho',
        'andres.munoz@casas.cl',
        'Solar',
        'Usado',
        -29.904053,
        -71.249070
    ),
    (
        'Departamento en Antofagasta',
        'Moderno departamento con vista al mar.',
        'Apartamento',
        'Antofagasta, Antofagasta',
        200000000,
        4,
        3,
        180,
        '2024-03-10',
        TRUE,
        6,
        2,
        TRUE,
        TRUE,
        TRUE,
        NULL,
        'Piscina y áreas comunes',
        'valeria.rojas@gmail.com',
        'Eléctrica',
        'Nuevo',
        -23.650000,
        -70.400000
    ),
    (
        'Terreno en Pucón',
        'Terreno ideal para cabañas de turismo.',
        'Terreno',
        'Pucón, Araucanía',
        150000000,
        0,
        0,
        1500,
        '2024-02-15',
        TRUE,
        NULL,
        NULL,
        FALSE,
        FALSE,
        FALSE,
        NULL,
        'Cercano al centro y termas',
        'fernanda.gomez@inmobiliaria.cl',
        'N/A',
        'Nuevo',
        -39.282444,
        -71.972890
    ),
    (
        'Casa en Concepción',
        'Casa amplia cerca del centro de la ciudad.',
        'Casa',
        'Concepción, Biobío',
        98000000,
        4,
        2,
        180,
        '2024-01-28',
        TRUE,
        20,
        2,
        TRUE,
        TRUE,
        TRUE,
        25,
        'Estacionamiento para 2 autos',
        'jose.castro@hogares.cl',
        'Convencional',
        'Usado',
        -36.826992,
        -73.049773
    ),
    (
        'Departamento en Iquique',
        'Departamento con vista a Playa Cavancha.',
        'Apartamento',
        'Iquique, Tarapacá',
        220000000,
        3,
        3,
        120,
        '2024-02-25',
        TRUE,
        5,
        2,
        TRUE,
        FALSE,
        TRUE,
        20,
        'Piscina y sauna',
        'paula.silva@iquique.cl',
        'Solar',
        'Nuevo',
        -20.220315,
        -70.138073
    ),
    (
        'Terreno en Villarrica',
        'Terreno amplio con acceso al lago.',
        'Terreno',
        'Villarrica, Araucanía',
        190000000,
        0,
        0,
        1800,
        '2024-03-15',
        TRUE,
        NULL,
        NULL,
        FALSE,
        FALSE,
        FALSE,
        NULL,
        'Ubicación privilegiada',
        'francisco.miranda@terrenos.cl',
        'N/A',
        'Nuevo',
        -39.281631,
        -72.227898
    ),
    (
        'Casa en Punta Arenas',
        'Casa cálida y acogedora en sector residencial.',
        'Casa',
        'Punta Arenas, Magallanes',
        85000000,
        3,
        1,
        120,
        '2024-01-10',
        TRUE,
        30,
        1,
        TRUE,
        FALSE,
        TRUE,
        15,
        'Chimenea y jardín trasero',
        'elena.valenzuela@gmail.com',
        'Convencional',
        'Usado',
        -53.163833,
        -70.917068
    ),
    (
        'Departamento en Chillán',
        'Cercano a universidades y transporte público.',
        'Apartamento',
        'Chillán, Ñuble',
        75000000,
        2,
        1,
        75,
        '2024-02-12',
        TRUE,
        8,
        1,
        TRUE,
        FALSE,
        FALSE,
        NULL,
        'Gastos comunes bajos',
        'matias.vera@chillan.cl',
        'Convencional',
        'Usado',
        -36.606261,
        -72.103421
    ),
    (
        'Terreno en Puerto Montt',
        'Terreno amplio en zona industrial.',
        'Terreno',
        'Puerto Montt, Los Lagos',
        120000000,
        0,
        0,
        3000,
        '2024-03-01',
        TRUE,
        NULL,
        NULL,
        FALSE,
        FALSE,
        FALSE,
        NULL,
        'Acceso directo a carretera',
        'camilo.ruiz@terrenos.com',
        'N/A',
        'Nuevo',
        -41.468917,
        -72.941136
    ),
    (
        'Casa en Temuco',
        'Casa en barrio tranquilo cerca del centro.',
        'Casa',
        'Temuco, Araucanía',
        90000000,
        3,
        2,
        150,
        '2024-04-05',
        TRUE,
        18,
        1,
        TRUE,
        TRUE,
        TRUE,
        20,
        'Cercano a colegios y supermercados',
        'carolina.diaz@gmail.com',
        'Solar',
        'Usado',
        -38.735901,
        -72.590373
    ),
    (
        'Departamento en Coquimbo',
        'Con vista a la bahía, cercano a la playa.',
        'Apartamento',
        'Coquimbo, Coquimbo',
        98000000,
        3,
        2,
        100,
        '2024-02-20',
        TRUE,
        4,
        1,
        TRUE,
        TRUE,
        TRUE,
        NULL,
        'Áreas comunes con quincho',
        'felipe.morales@coquimbo.cl',
        'Eléctrica',
        'Nuevo',
        -29.953295,
        -71.339718
    ),
    (
        'Terreno en Osorno',
        'Terreno ideal para proyecto agrícola.',
        'Terreno',
        'Osorno, Los Lagos',
        100000000,
        0,
        0,
        2500,
        '2024-03-20',
        TRUE,
        NULL,
        NULL,
        FALSE,
        FALSE,
        FALSE,
        NULL,
        'Buena calidad de suelo',
        'isabel.martinez@terrenos.cl',
        'N/A',
        'Nuevo',
        -40.574286,
        -73.134327
    ),
    (
        'Casa con vista al mar',
        'Casa con amplios ventanales y espectacular vista al océano.',
        'Casa',
        'Viña del Mar, Valparaíso',
        185000000.00,
        4,
        3,
        300,
        '2024-05-01',
        TRUE,
        10,
        2,
        TRUE,
        TRUE,
        TRUE,
        80,
        'Piscina y quincho',
        'contacto@casamar.cl',
        'Solar',
        'Usado',
        -33.015348,
        -71.550027
    ),
    (
        'Departamento céntrico',
        'Moderno y cercano a la estación de metro.',
        'Apartamento',
        'Santiago Centro, Santiago',
        85000000.00,
        2,
        2,
        65,
        '2024-06-15',
        TRUE,
        3,
        1,
        FALSE,
        FALSE,
        TRUE,
        5,
        'Seguridad 24/7',
        'ventas@urbano.cl',
        'Eléctrica',
        'Nuevo',
        -33.448890,
        -70.669265
    ),
    (
        'Parcela de agrado',
        'Terreno con casa estilo campestre.',
        'Casa',
        'Osorno, Los Lagos',
        150000000.00,
        5,
        3,
        400,
        '2024-05-20',
        TRUE,
        15,
        1,
        TRUE,
        TRUE,
        TRUE,
        150,
        'Huerto y establo',
        'camposur@parcelas.cl',
        'Convencional',
        'Usado',
        -40.573065,
        -73.127759
    ),
    (
        'Terreno urbano',
        'Terreno plano con acceso a servicios básicos.',
        'Terreno',
        'Temuco, Araucanía',
        55000000.00,
        0,
        0,
        800,
        '2024-06-01',
        TRUE,
        NULL,
        NULL,
        FALSE,
        FALSE,
        FALSE,
        NULL,
        'Cercano a colegios',
        'ventas@terrenosaraucania.cl',
        'N/A',
        'Nuevo',
        -38.739650,
        -72.598420
    ),
    (
        'Casa en condominio',
        'Moderna y segura, con áreas verdes comunes.',
        'Casa',
        'La Serena, Coquimbo',
        130000000.00,
        3,
        2,
        140,
        '2024-05-10',
        TRUE,
        8,
        2,
        TRUE,
        TRUE,
        FALSE,
        20,
        'Juegos infantiles y piscina',
        'contacto@serenacasas.cl',
        'Solar',
        'Usado',
        -29.904530,
        -71.248941
    ),
    (
        'Departamento vista cordillera',
        'Luminoso, ideal para familias pequeñas.',
        'Apartamento',
        'Providencia, Santiago',
        98000000.00,
        2,
        2,
        75,
        '2024-06-20',
        TRUE,
        6,
        1,
        TRUE,
        FALSE,
        TRUE,
        10,
        'Gimnasio y sala multiuso',
        'propiedades@cordillera.cl',
        'Eléctrica',
        'Usado',
        -33.431447,
        -70.609332
    ),
    (
        'Casa en el sur',
        'Acogedora cabaña con chimenea en la Región de Los Ríos.',
        'Casa',
        'Valdivia, Los Ríos',
        92000000.00,
        3,
        2,
        160,
        '2024-05-05',
        TRUE,
        12,
        1,
        TRUE,
        TRUE,
        TRUE,
        50,
        'Bodega y leñera',
        'ventasur@propiedades.cl',
        'Convencional',
        'Usado',
        -39.819585,
        -73.245210
    ),
    (
        'Terreno comercial',
        'Terreno ideal para inversión en zona céntrica.',
        'Terreno',
        'Antofagasta, Antofagasta',
        200000000.00,
        0,
        0,
        1200,
        '2024-06-10',
        TRUE,
        NULL,
        NULL,
        FALSE,
        FALSE,
        FALSE,
        NULL,
        'Cercano a avenidas principales',
        'ventas@terrenosnorte.cl',
        'N/A',
        'Nuevo',
        -23.650000,
        -70.400000
    ),
    (
        'Departamento en la playa',
        'Amplio y con acceso directo al mar.',
        'Apartamento',
        'Iquique, Tarapacá',
        115000000.00,
        3,
        2,
        100,
        '2024-05-25',
        TRUE,
        7,
        1,
        TRUE,
        TRUE,
        TRUE,
        15,
        'Piscina y estacionamiento',
        'ventas@iquiquedepartamentos.cl',
        'Solar',
        'Usado',
        -20.230703,
        -70.135669
    ),
    (
        'Casa con patio amplio',
        'Ideal para familias numerosas.',
        'Casa',
        'Rancagua, O’Higgins',
        105000000.00,
        4,
        3,
        200,
        '2024-05-30',
        TRUE,
        20,
        1,
        TRUE,
        TRUE,
        TRUE,
        70,
        'Terraza techada',
        'contacto@casasrancagua.cl',
        'Convencional',
        'Usado',
        -34.170132,
        -70.744506
    ),
    (
        'Parcela turística',
        'Perfecta para proyectos turísticos o familiares.',
        'Terreno',
        'Puerto Varas, Los Lagos',
        160000000.00,
        0,
        0,
        2500,
        '2024-06-15',
        TRUE,
        NULL,
        NULL,
        FALSE,
        FALSE,
        FALSE,
        NULL,
        'Vista al lago',
        'ventas@terrenosur.cl',
        'N/A',
        'Nuevo',
        -41.322406,
        -72.987438
    ),
    (
        'Departamento económico',
        'Práctico y cercano a transporte público.',
        'Apartamento',
        'Quilpué, Valparaíso',
        55000000.00,
        1,
        1,
        40,
        '2024-05-12',
        TRUE,
        2,
        1,
        FALSE,
        FALSE,
        FALSE,
        NULL,
        'Sin estacionamiento',
        'ventas@quilpuedepartamentos.cl',
        'Eléctrica',
        'Nuevo',
        -33.048712,
        -71.438121
    ),
    (
        'Casa en barrio residencial',
        'Cerca de parques y colegios.',
        'Casa',
        'Concepción, Biobío',
        125000000.00,
        3,
        3,
        180,
        '2024-06-05',
        TRUE,
        15,
        1,
        TRUE,
        TRUE,
        TRUE,
        35,
        'Jardín y quincho',
        'contacto@biobiocasas.cl',
        'Solar',
        'Usado',
        -36.827000,
        -73.050000
    ),
    (
        'Terreno para proyectos',
        'Zona en desarrollo con gran potencial.',
        'Terreno',
        'Copiapó, Atacama',
        48000000.00,
        0,
        0,
        1000,
        '2024-06-20',
        TRUE,
        NULL,
        NULL,
        FALSE,
        FALSE,
        FALSE,
        NULL,
        'Acceso asfaltado',
        'ventas@terrenoscopiapo.cl',
        'N/A',
        'Nuevo',
        -27.366796,
        -70.332206
    ),
    (
        'Casa con piscina',
        'Perfecta para el verano y reuniones sociales.',
        'Casa',
        'Chillán, Ñuble',
        89000000.00,
        3,
        2,
        150,
        '2024-05-15',
        TRUE,
        10,
        1,
        TRUE,
        TRUE,
        TRUE,
        40,
        'Piscina temperada',
        'ventas@chillanpropiedades.cl',
        'Eléctrica',
        'Usado',
        -36.606378,
        -72.102790
    );

-- Gestión de libros
CREATE DATABASE gestion_libros;

\c vida_sana;

CREATE TABLE books (
    id SERIAL,
    title VARCHAR(50) NOT NULL,
    book_description VARCHAR(250) NOT NULL,
    author VARCHAR(250) NOT NULL
);

INSERT INTO
    books (
        title,
        book_description,
        author
    )
values (
        'Libro1',
        'Descripción libro 1',
        'Autor libro 1'
    ),
    (
        'Libro2',
        'Descripción libro 2',
        'Autor libro 2'
    ),
    (
        'Libro3',
        'Descripción libro 3',
        'Autor libro 3'
    )

-- ROLES Admin (Administrator) Librarian (Librarian) User (Registered User) Guest (Guest User)
DROP TABLE users;

CREATE TABLE users (
    id SERIAL,
    email VARCHAR(50) NOT NULL,
    email_verified BOOLEAN DEFAULT FALSE,
    password VARCHAR(60) NOT NULL,
    role VARCHAR(20) DEFAULT 'USER' CHECK (
        role IN (
            'ADMIN',
            'LIBRARIAN',
            'USER',
            'GUEST'
        )
    )
);

INSERT INTO
    users (email, password)
values ('admin@books.com', '123456'),
    (
        'manager@books.com',
        'abcdefg'
    );

SELECT * FROM books;

SELECT * FROM users;

CREATE TABLE email_verifications (
    id SERIAL,
    email VARCHAR(255) UNIQUE NOT NULL PRIMARY KEY,
    token UUID NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    user_id INT NOT NULL
);